name: cicd

on:
  pull_request:
    branches:
      - develop

jobs:
  ci-pr:
    uses: node-real/github-workflows/.github/workflows/ci-pr.yml@v1
    secrets: inherit
    with:
      ci-lint-skip: true
      ci-test-skip: true
      build-platform: linux/amd64
      image-repo-name: bsc
      dockerfile: Dockerfile
