name: Docker Image CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: [self-hosted,prod-cicd-runners]
    steps:
      - uses: actions/checkout@v2
      - name: Build, tag, and push image to Amazon ECR
        run: |
          aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com
          docker build --build-arg profile=prod --build-arg GIT_TOKEN=${{ secrets.GO_MODULES_TOKEN }} -t ${ECR_REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com/bsc:${GITHUB_SHA} .
          docker push "${ECR_REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com/bsc:${GITHUB_SHA}"
