name: Integration Test

on:
  push:
    branches: 
      - master
      - develop
      - state_expiry_mvp0.1_dev

  pull_request:
    branches: 
      - master
      - develop
      - state_expiry_mvp0.1_dev

jobs:
  truffle-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Truffle test
      run: |
        make truffle-test
