name: Lint

on:
  push:
    branches: 
      - master
      - develop

  pull_request:
    branches: 
      - master
      - develop

jobs:
  golang-lint:
    runs-on: [prod-cicd-runners]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a one-line script
      run: aws s3 ls s3://tf-nodereal-prod-nodereal-static/*
